version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - DB_DATABASE=product-db
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: product-db
    ports:
      - 3306:3306
  app:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    ports:
      - "3000:8000"
    command: yarn serve
    environment:
      NODE_ENV: development
    volumes:
      - ./app:/home/node/app
    depends_on:
      - api
